version: '3.7'

services:
  api:
    build:
      context: ./docker/rust
      target: 'develop-stage'
    ports:
      - "8080:80"

    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"


  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: database
      


volumes:
  cargo-cache:
  target-cache: