version: '3.7'

services:
  api:
    build:
      context: ./docker/rust
      target: 'develop-stage'
    ports:
      - "8080:80"

    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

  db:
    build:
      context: ./docker/mariadb
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo


volumes:
  cargo-cache:
  target-cache: